[build]
builder = "nixpacks"
buildCommand = "npm install --production && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/_health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 