services:
  - type: web
    name: strapi-backend
    env: node
    buildCommand: |
      npm cache clean --force
      rm -rf node_modules package-lock.json
      npm install ajv@8.12.0 ajv-draft-04@1.0.0 ajv-formats@2.1.1 --legacy-peer-deps --no-audit --no-fund
      npm install --legacy-peer-deps --no-audit --no-fund --prefer-offline
      npm rebuild
      NODE_ENV=development NODE_OPTIONS='--max-old-space-size=2048' npm run build
    startCommand: NODE_OPTIONS='--max-old-space-size=2048' npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: strapi-db
          property: connectionString
      - key: DATABASE_SSL
        value: "false"
      - key: STRAPI_API_TOKEN
        sync: false
    healthCheckPath: /_health
    autoDeploy: true
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: strapi-disk
      mountPath: /opt/render/project/src/.tmp
      sizeGB: 1
