services:
  - type: web
    name: strapi-backend
    env: node
    buildCommand: NODE_OPTIONS='--max-old-space-size=256' npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: strapi-db
          property: connectionString
      - key: STRAPI_API_TOKEN
        sync: false
    healthCheckPath: /_health
    autoDeploy: true
    plan: free
    scaling:
      minInstances: 1
      maxInstances: 1
