services:
  - type: web
    name: strapi-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: strapi-db
          property: connectionString
    healthCheckPath: /_health
    autoDeploy: true
